---
- name: Install Python3 and docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/pthon
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present

