---
- name: Install Python3, docker and docker-compose
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/pthon
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose
   
- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user
      user:
        name: ec2-user
        group: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Start docker container
  hosts: docker_server
  tasks:
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
    - name: copy docker compose
      copy:
        src: /Documents/nana/ansible/bootcamp-java-mysql-project/docker-compose-full.yaml
        dest: /usr/ec2-user/docker-compose.yaml
    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: monirerahmani
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present